name: CI pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome88-ff89

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2.3.1

    - name: Install Dependencies 🔧
      run: yarn

    - name: Run Tests ✅
      run: yarn workspaces run test

    - uses: actions/upload-artifact@v2
      name: Upload Cypress screenshots if tests failed 🤕
      if: failure()
      with:
        name: cypress-screenshots
        path: "**/__image_snapshots__"
