name: CI (on PRs and master branch)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  IS_PR_WITH_PERCY: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.title, 'no-percy') && !contains(github.event.pull_request.body, 'no-percy') }}
  IS_PR_JUST_MERGED: ${{ github.ref_name == 'master' && contains(github.event.head_commit.message, 'Merge pull request') && !contains(github.event.head_commit.message, 'no-percy') }}

jobs:
  build:
    runs-on: ubuntu-latest # note: macos doesn't have docker installed!
    container: cypress/browsers:node14.17.0-chrome91-ff89

    steps:
      - name: Log Interesting Info ℹ️
        run: |
          echo "The job is triggered by a ${{ github.event_name }} event."
          echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"

      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install Dependencies 🔧
        run: yarn

      - name: Type Check ʦ
        run: yarn run type-check

      - name: Linting 🕵
        run: yarn run lint

      - name: Formatting 📏
        run: yarn run format:check

      - name: Build 🔨
        run: yarn run build:public

      - name: Run Tests ✅
        if: ${{ env.IS_PR_JUST_MERGED == 'true' || env.IS_PR_WITH_PERCY == 'true' }}
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        run: yarn run test

      - name: Run Tests (without percy) ✅
        if: ${{ !(env.IS_PR_JUST_MERGED == 'true' || env.IS_PR_WITH_PERCY == 'true') }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        run: yarn run test

      - uses: actions/upload-artifact@v2
        name: Upload Cypress screenshots if tests failed 🤕
        if: failure()
        with:
          name: cypress-screenshots
          path: |
            packages/jui/**/__image_snapshots__
            packages/jui/cypress/videos
            packages/jui/cypress/screenshots
