name: Retain docs by tag
on:
  push:
    tags:
      - "docs/*"
jobs:
  deploy-website:
    name: Deploy website to Github Pages to sub-folder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - id: setTargetFolder
        run: |
          tag_without_prefix=$(echo ${{ github.ref_name }} |  cut -b 6-);
          echo "tag_without_prefix: $tag_without_prefix"
          echo "targetFolder=-/$tag_without_prefix" >> $GITHUB_OUTPUT

      - name: Install and Build 🔧
        run: |
          yarn
          export WEBSITE_BASE_URL="/jui/${{steps.setTargetFolder.outputs.targetFolder}}/"
          echo "WEBSITE_BASE_URL: $WEBSITE_BASE_URL"
          yarn workspace website run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: packages/website/build
          target-folder: ${{steps.setTargetFolder.outputs.targetFolder}}
